/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package utfpr.gui;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import utfpr.banco.Banco;
import utfpr.banco.ContaBancaria;
import utfpr.banco.Cliente;

/**
 *
 * @author Gabriel
 */
public class IJLista extends javax.swing.JInternalFrame {

    DefaultListModel Model = new DefaultListModel();
    Banco JIBanco;
    ArrayList<Integer> listaClientes = new ArrayList<>();
    ArrayList<ContaBancaria> listaContas = new ArrayList<>();

    /**
     * Creates new form IJLista
     */
    public IJLista() {
        initComponents();
        this.lstLista.setModel(Model);
    }

    public void receberBanco(Banco JIBanco) {
        this.JIBanco = JIBanco;
    }

    public void listarContas() {
        int contagem = 1;
        while (true) {
            ContaBancaria conta = JIBanco.getConta(contagem);
            if (conta == null) {
                break;
            }
            if (!(listaContas.contains(conta))) {
                listaContas.add(conta);
                Model.addElement(conta.getInformacoes());
            }
            contagem++;
        }
    }

    public void listarClientes() {
        int contagem = 1;

        while (true) {
            ContaBancaria conta = JIBanco.getConta(contagem);
            if (conta == null) {
                break;
            }
            Cliente cliente = conta.getTitular();
            if (!(listaClientes.contains(cliente.getCod()))) {
                listaClientes.add(cliente.getCod());
                Model.addElement(cliente.toString());
            }
            contagem++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstLista = new javax.swing.JList<>();

        setForeground(new java.awt.Color(240, 240, 240));
        setTitle("Resultado");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(1265, 680));
        setMinimumSize(new java.awt.Dimension(1265, 680));
        setPreferredSize(new java.awt.Dimension(1265, 680));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(1265, 680));

        lstLista.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lstLista.setMaximumSize(new java.awt.Dimension(1265, 680));
        lstLista.setMinimumSize(new java.awt.Dimension(1265, 680));
        lstLista.setPreferredSize(new java.awt.Dimension(1265, 680));
        jScrollPane1.setViewportView(lstLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstLista;
    // End of variables declaration//GEN-END:variables
}
