/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utfpr.gui;

import java.awt.Dialog;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utfpr.banco.Banco;

/**
 *
 * @author Gabriel
 */
public class Principal extends javax.swing.JFrame {

    Banco JBanco;
    JDialog clientesPopUp = new JDialog(), contasPopUp = new JDialog();
    IJLista listaCliente = new IJLista(), listaConta = new IJLista();

    /**
     * Creates new form Janelainicial
     */
    public Principal() {
        initComponents();

        clientesPopUp.setAutoRequestFocus(true);
        contasPopUp.setAutoRequestFocus(true);
        clientesPopUp.setSize(this.getSize());
        contasPopUp.setSize(this.getSize());
        clientesPopUp.setResizable(false);
        contasPopUp.setResizable(false);
        clientesPopUp.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        contasPopUp.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        clientesPopUp.setLocation(this.getLocation());
        contasPopUp.setLocation(this.getLocation());
        clientesPopUp.setTitle("Cadastros de Clientes");
        contasPopUp.setTitle("Cadastros de Contas Bancárias");
    }

    public void passarBanco(Banco JBanco) {
        this.JBanco = JBanco;
        txtBanco.setText(JBanco.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBanco = new java.awt.Label();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuListarCliente = new javax.swing.JMenuItem();
        jMenuListarConta = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuRelContas = new javax.swing.JMenu();
        jMenuContaMenorSaldo = new javax.swing.JMenuItem();
        jMenuContaMaiorSaldo = new javax.swing.JMenuItem();
        jMenuMediaSaldo = new javax.swing.JMenuItem();
        jMenuMediaSaldoCC = new javax.swing.JMenuItem();
        jMenuMediaSaldoCP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoonBank App  v1.0");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setName("principal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        setState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        txtBanco.setAlignment(java.awt.Label.CENTER);
        txtBanco.setFont(new java.awt.Font("Courier New", 1, 72)); // NOI18N
        txtBanco.setName(""); // NOI18N
        txtBanco.setPreferredSize(new java.awt.Dimension(1280, 700));
        txtBanco.setText("txtBanco");
        getContentPane().add(txtBanco);

        jMenuBar.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jMenuBar.setMaximumSize(new java.awt.Dimension(25, 32768));
        jMenuBar.setMinimumSize(new java.awt.Dimension(65, 19));
        jMenuBar.setPreferredSize(new java.awt.Dimension(65, 19));

        jMenuCadastros.setText("Cadastros");

        jMenuListarCliente.setText("Lista de Clientes");
        jMenuListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuListarCliente);

        jMenuListarConta.setText("Lista de Contas");
        jMenuListarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarContaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuListarConta);

        jMenuBar.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatórios");

        jMenuRelContas.setText("Contas");

        jMenuContaMenorSaldo.setText("Conta com o Menor Saldo");
        jMenuContaMenorSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaMenorSaldoActionPerformed(evt);
            }
        });
        jMenuRelContas.add(jMenuContaMenorSaldo);

        jMenuContaMaiorSaldo.setText("Conta com o Maior Saldo");
        jMenuContaMaiorSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaMaiorSaldoActionPerformed(evt);
            }
        });
        jMenuRelContas.add(jMenuContaMaiorSaldo);

        jMenuMediaSaldo.setText("Média de Saldos (Geral)");
        jMenuMediaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMediaSaldoActionPerformed(evt);
            }
        });
        jMenuRelContas.add(jMenuMediaSaldo);

        jMenuMediaSaldoCC.setText("Média de Saldos (Apenas CC)");
        jMenuMediaSaldoCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMediaSaldoCCActionPerformed(evt);
            }
        });
        jMenuRelContas.add(jMenuMediaSaldoCC);

        jMenuMediaSaldoCP.setText("Média de Saldos (Apenas CP)");
        jMenuMediaSaldoCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMediaSaldoCPActionPerformed(evt);
            }
        });
        jMenuRelContas.add(jMenuMediaSaldoCP);

        jMenuRelatorios.add(jMenuRelContas);

        jMenuBar.add(jMenuRelatorios);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuListarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarContaActionPerformed
        listaConta.setEnabled(false);
        listaConta.setTitle("");
        listaConta.receberBanco(JBanco);
        listaConta.listarContas();
        contasPopUp.add(listaConta);
        listaConta.setVisible(true);
        contasPopUp.setVisible(true);
    }//GEN-LAST:event_jMenuListarContaActionPerformed

    private void jMenuListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarClienteActionPerformed
        listaCliente.setEnabled(false);
        listaCliente.setTitle("");
        listaCliente.receberBanco(JBanco);
        listaCliente.listarClientes();
        clientesPopUp.add(listaCliente);
        listaCliente.setVisible(true);
        clientesPopUp.setVisible(true);
    }//GEN-LAST:event_jMenuListarClienteActionPerformed

    private void jMenuContaMenorSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaMenorSaldoActionPerformed
        JOptionPane.showMessageDialog(this, JBanco.menorSaldo(), "Conta Com o Menor Saldo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuContaMenorSaldoActionPerformed

    private void jMenuContaMaiorSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaMaiorSaldoActionPerformed
        JOptionPane.showMessageDialog(this, JBanco.maiorSaldo(), "Conta Com o Maior Saldo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuContaMaiorSaldoActionPerformed

    private void jMenuMediaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMediaSaldoActionPerformed
        JOptionPane.showMessageDialog(this, JBanco.mediaSaldoCB(), "Média de Saldos (Geral)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuMediaSaldoActionPerformed

    private void jMenuMediaSaldoCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMediaSaldoCCActionPerformed
        JOptionPane.showMessageDialog(this, JBanco.mediaSaldoCC(), "Média de Saldos (Apenas CC)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuMediaSaldoCCActionPerformed

    private void jMenuMediaSaldoCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMediaSaldoCPActionPerformed
        JOptionPane.showMessageDialog(this, JBanco.mediaSaldoCP(), "Média de Saldos (Apenas CP)", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuMediaSaldoCPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuContaMaiorSaldo;
    private javax.swing.JMenuItem jMenuContaMenorSaldo;
    private javax.swing.JMenuItem jMenuListarCliente;
    private javax.swing.JMenuItem jMenuListarConta;
    private javax.swing.JMenuItem jMenuMediaSaldo;
    private javax.swing.JMenuItem jMenuMediaSaldoCC;
    private javax.swing.JMenuItem jMenuMediaSaldoCP;
    private javax.swing.JMenu jMenuRelContas;
    private javax.swing.JMenu jMenuRelatorios;
    private java.awt.Label txtBanco;
    // End of variables declaration//GEN-END:variables
}
